### ISSUE TITLE
HaystackTracerBundle is not currently useable.

### ISSUE THREAD

**Issue by amcghie** [ExpediaDotCom/haystack-dropwizard#9]
Until the following issue with `haystack-java-client` is resolved https://github.com/ExpediaDotCom/haystack-client-java/issues/105 `HaystackTracerBundle` cannot be used as it does not override the `DEFAULT_ID_GENERATOR` defined in `com.expedia.www.haystack.client.Tracer`.  This results in the following stack trace being generated for any downstream services also using `haystack-java-client`:
```
ERROR [2019-06-05 11:34:58,957] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 9747e8d6c092bd0b
! java.lang.IllegalArgumentException: Invalid UUID string: 1560033070049436460
! at java.util.UUID.fromString(UUID.java:194)
! at com.expedia.www.haystack.client.propagation.TextMapPropagator.extract(TextMapPropagator.java:101)
! at com.expedia.www.haystack.client.propagation.TextMapPropagator.extract(TextMapPropagator.java:30)
! at com.expedia.www.haystack.client.Tracer.extract(Tracer.java:185)
! at com.expedia.www.haystack.client.Tracer.extract(Tracer.java:43)
! at io.opentracing.contrib.jaxrs2.server.ServerTracingFilter.parentSpanContext(ServerTracingFilter.java:99)
! at io.opentracing.contrib.jaxrs2.server.ServerTracingFilter.filter(ServerTracingFilter.java:68)
```
This can be easily replicated by running the example in https://github.com/ExpediaDotCom/haystack-dropwizard-example

**Comment by shreyaa-sharma** [comment]
Closing this as the PR seems to be merged.
